# Generated by Django 4.0.2 on 2022-02-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('faible', 'faible'), ('moyenne', 'moyenne'), ('élevée', 'élevée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('à faire', 'à faire'), ('en cours', 'en cours'), ('terminé', 'terminé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('amelioration', 'amélioration'), ('tâche', 'tâche')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
