# Generated by Django 4.0.2 on 2022-02-10 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='project_id',
        ),
        migrations.AddField(
            model_name='contributors',
            name='project_id',
            field=models.ManyToManyField(to='softdesk.Projects'),
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contributors',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
